### ISSUE TITLE
How to export the stream map as a data array?

### ISSUE THREAD

**Issue by wanggy-1** [weigert/SimpleHydrology#12]
Thank you for sharing this excellent work!

I'm trying to build some 3D river channel models based on your work, so I need to know the river positions on the map. Is there any way to export a stream map like this as a data array? Also, do these streams have pixel-wise water depth data? If they do, how can I export the water depth data?
![fig](https://github.com/weigert/SimpleHydrology/assets/64789033/77795fa5-98f7-4c56-9ce8-a877012dc624)

**Comment by weigert** [comment]
Hi @wanggy-1. This iteration of the SimpleHydrology is meant to be visually runnable. For a pure data / io version, see https://github.com/erosiv/soillib. Cheers

You will want to run the first example, `basic_hydrology`. Note that to export the images, you have to create the `out` directory first.
