### ISSUE TITLE
Can't compile, "Buffer" not declared anywhere

### ISSUE THREAD

**Issue by chmjwl** [weigert/SimpleHydrology#6]
I'm trying to compile the current master (01dde83), using the current master of TinyEngine cd43198, but I get this error:

```
SimpleHydrology.cpp:53:2: error: ‘Buffer’ was not declared in this scope
   53 |  Buffer modelbuf;
      |  ^~~~~~
```

I could find no reference to a "Buffer" in the code.

**Comment by weigert** [comment]
Hi,

I apologize but the working branch of TinyEngine where I implemented the buffer class was not yet merged into main. If you look now, the branch has been merged and SimpleHydrology should be compileable using the current main branch of TinyEngine.

Thanks for the info! Let me know if this resolves the issue.
